jobs:
  docker:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      id: meta
      name: Docker meta
      uses: docker/metadata-action@v4
      with:
        images: rsksmart/rskj
        tags: 'type=ref,event=branch

          type=ref,event=tag

          type=edge

          # This is used for generating IRIS-3 out of IRIS-3.x.y.

          type=match,pattern=(\w+-\d+)\.\d+\.\d+.*,group=1

          '
    - continue-on-error: true
      name: DockerHub login
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
    - continue-on-error: true
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        labels: ${{ steps.meta.outputs.labels }}
        push: false
        tags: ${{ steps.meta.outputs.tags }}
name: Docker image
on:
  repository_dispatch:
    types: trigger-ga___docker.yml
